version: 2.1
jobs:
  node:
    working_directory: ~/react-native-circle
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
    
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths: 
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: yarn test

  android:
    working_directory: ~/react-native-circle/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - run:
          name: Build Android
          working_directory: android
          command: ./gradlew assembleRelease

workflows:
  build:
    jobs:
      - node
      - android:
          requires:
            - node
